#pragma once

static constexpr std::array c_HeaderFiles {
  "deps.h",
  "defs.hh",
  "types.hh",
  "metaprogramming.hh",
  "version.h",
  "assert.h",
  "defer.hh",
  "memory.h",
  "coroutine.h",
  "math.h",
  "math_vec2.h", "math_vec2.hh",
  "math_vec3.h", "math_vec3.hh",
  "math_vec4.h", "math_vec4.hh",
  "math_quat.h", "math_quat.hh",
  "math_rect.h", "math_rect.hh",
  "math_mat4.h", "math_mat4.hh",
  "math_mat.h",
  "sort.h",
  "rng.h",
  "crypto.h",
  "log.hh",
  "should.h",
  "time.h",
  "chrono.hh",
  "string.h", "string.hh",
  "span.h", "span.hh",
  "strview.h", "strview.hh",
  "list.h", "list.hh",
  "circularqueue.hh",
  "hashmap.h",
  "slotmap.h", "slotmap.hh",
  "strlist.hh",
  "ui.h",
  "font.h", "font.hh",
  "mesh.h", "mesh.hh",
  "camera.h", "camera.hh",
  "image.h", "image.hh",
  "win.hh",
  "drawcanvas.h", "drawcanvas.hh",
  "sprite.h", "sprite.hh",
  "color.h",
  "fs.h", "fs.hh",
  "net.h",
  "socket.hh",
  "audio.hh",
  "sprite_manager.hh",
  "mesh_manager.hh",
  "nn.h",
  "test_manager.h",
  "junit.h",
  "skap.h", "skap.hh",
  "aliases.hh",
};
